POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username" : "Hanna1",
  "password" : "hanna"
}

### 

POST http://localhost:5000/api/auth/login
Content-Type:  application/json

{
  "username": "Ly",
  "password": "lý"
}

###

POST http://localhost:5000/api/post
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmFhYzljMjA4NWJhZTMzZjcyNjcwNWMiLCJpYXQiOjE2NTU0NTU4MjR9.sU6rJN7nLHeufzC-3txU0JWYU3NIA8Ha8IQNkXPxYXM

{
  "title": "my firt post",
  "description": "abc",
  "url": "google.com",
  "status": "Learning"
}